//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Inputsystem/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""PlayerControls"",
            ""id"": ""8d15f648-d495-43df-8064-8307b7592350"",
            ""actions"": [
                {
                    ""name"": ""Root"",
                    ""type"": ""Button"",
                    ""id"": ""d8ddbfbe-f502-4a5d-9180-97eaa5220eaf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""fa62b335-5b60-40ba-8c08-6d173658a980"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""26e36fc7-02f7-46c8-934f-c7d0244a2b07"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""7f62f32c-46f4-4260-9bd9-17f2f8954d1d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnRoot"",
                    ""type"": ""Button"",
                    ""id"": ""10572c45-920a-41e6-a685-1dc333b2c885"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""22f2d2b4-14c6-40dd-a24c-d8d25e0d9e78"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Root"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd4c803c-a9cb-490a-a76a-2e2775cd7b1e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d09830b7-7d25-463f-8e61-e073f14a5385"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db4e70fb-d8bf-4cbf-9d98-9e7c8d03f706"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30930914-e024-410d-86db-5dd16f00c3ae"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""579cfd3a-efe0-4f2a-8991-283314cf1c1b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63696c84-2063-44a6-bb34-f9787b77fe60"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnRoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Rooted"",
            ""id"": ""1de20a06-609c-482c-ad3a-5468910ff054"",
            ""actions"": [
                {
                    ""name"": ""Grow"",
                    ""type"": ""Button"",
                    ""id"": ""027a8b49-fe5c-4bac-a8c3-6077359f0af1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""a8327593-0cfd-4899-b091-78533a55fe06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""9ee80fdc-2f28-461f-8262-3ca741bf83e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""849477f0-75dc-426a-ac95-f83a70ad648a"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e8e907b-cb5d-4ec6-a5aa-c3d5f4df8398"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed676d93-f0c8-423e-8701-e77db5f4049d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControls
        m_PlayerControls = asset.FindActionMap("PlayerControls", throwIfNotFound: true);
        m_PlayerControls_Root = m_PlayerControls.FindAction("Root", throwIfNotFound: true);
        m_PlayerControls_Left = m_PlayerControls.FindAction("Left", throwIfNotFound: true);
        m_PlayerControls_Right = m_PlayerControls.FindAction("Right", throwIfNotFound: true);
        m_PlayerControls_Jump = m_PlayerControls.FindAction("Jump", throwIfNotFound: true);
        m_PlayerControls_UnRoot = m_PlayerControls.FindAction("UnRoot", throwIfNotFound: true);
        // Rooted
        m_Rooted = asset.FindActionMap("Rooted", throwIfNotFound: true);
        m_Rooted_Grow = m_Rooted.FindAction("Grow", throwIfNotFound: true);
        m_Rooted_Left = m_Rooted.FindAction("Left", throwIfNotFound: true);
        m_Rooted_Right = m_Rooted.FindAction("Right", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControls
    private readonly InputActionMap m_PlayerControls;
    private IPlayerControlsActions m_PlayerControlsActionsCallbackInterface;
    private readonly InputAction m_PlayerControls_Root;
    private readonly InputAction m_PlayerControls_Left;
    private readonly InputAction m_PlayerControls_Right;
    private readonly InputAction m_PlayerControls_Jump;
    private readonly InputAction m_PlayerControls_UnRoot;
    public struct PlayerControlsActions
    {
        private @Player m_Wrapper;
        public PlayerControlsActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Root => m_Wrapper.m_PlayerControls_Root;
        public InputAction @Left => m_Wrapper.m_PlayerControls_Left;
        public InputAction @Right => m_Wrapper.m_PlayerControls_Right;
        public InputAction @Jump => m_Wrapper.m_PlayerControls_Jump;
        public InputAction @UnRoot => m_Wrapper.m_PlayerControls_UnRoot;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlsActions instance)
        {
            if (m_Wrapper.m_PlayerControlsActionsCallbackInterface != null)
            {
                @Root.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRoot;
                @Root.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRoot;
                @Root.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRoot;
                @Left.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeft;
                @Left.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeft;
                @Left.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeft;
                @Right.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRight;
                @Right.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRight;
                @Right.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRight;
                @Jump.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnJump;
                @UnRoot.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUnRoot;
                @UnRoot.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUnRoot;
                @UnRoot.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnUnRoot;
            }
            m_Wrapper.m_PlayerControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Root.started += instance.OnRoot;
                @Root.performed += instance.OnRoot;
                @Root.canceled += instance.OnRoot;
                @Left.started += instance.OnLeft;
                @Left.performed += instance.OnLeft;
                @Left.canceled += instance.OnLeft;
                @Right.started += instance.OnRight;
                @Right.performed += instance.OnRight;
                @Right.canceled += instance.OnRight;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @UnRoot.started += instance.OnUnRoot;
                @UnRoot.performed += instance.OnUnRoot;
                @UnRoot.canceled += instance.OnUnRoot;
            }
        }
    }
    public PlayerControlsActions @PlayerControls => new PlayerControlsActions(this);

    // Rooted
    private readonly InputActionMap m_Rooted;
    private IRootedActions m_RootedActionsCallbackInterface;
    private readonly InputAction m_Rooted_Grow;
    private readonly InputAction m_Rooted_Left;
    private readonly InputAction m_Rooted_Right;
    public struct RootedActions
    {
        private @Player m_Wrapper;
        public RootedActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Grow => m_Wrapper.m_Rooted_Grow;
        public InputAction @Left => m_Wrapper.m_Rooted_Left;
        public InputAction @Right => m_Wrapper.m_Rooted_Right;
        public InputActionMap Get() { return m_Wrapper.m_Rooted; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RootedActions set) { return set.Get(); }
        public void SetCallbacks(IRootedActions instance)
        {
            if (m_Wrapper.m_RootedActionsCallbackInterface != null)
            {
                @Grow.started -= m_Wrapper.m_RootedActionsCallbackInterface.OnGrow;
                @Grow.performed -= m_Wrapper.m_RootedActionsCallbackInterface.OnGrow;
                @Grow.canceled -= m_Wrapper.m_RootedActionsCallbackInterface.OnGrow;
                @Left.started -= m_Wrapper.m_RootedActionsCallbackInterface.OnLeft;
                @Left.performed -= m_Wrapper.m_RootedActionsCallbackInterface.OnLeft;
                @Left.canceled -= m_Wrapper.m_RootedActionsCallbackInterface.OnLeft;
                @Right.started -= m_Wrapper.m_RootedActionsCallbackInterface.OnRight;
                @Right.performed -= m_Wrapper.m_RootedActionsCallbackInterface.OnRight;
                @Right.canceled -= m_Wrapper.m_RootedActionsCallbackInterface.OnRight;
            }
            m_Wrapper.m_RootedActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Grow.started += instance.OnGrow;
                @Grow.performed += instance.OnGrow;
                @Grow.canceled += instance.OnGrow;
                @Left.started += instance.OnLeft;
                @Left.performed += instance.OnLeft;
                @Left.canceled += instance.OnLeft;
                @Right.started += instance.OnRight;
                @Right.performed += instance.OnRight;
                @Right.canceled += instance.OnRight;
            }
        }
    }
    public RootedActions @Rooted => new RootedActions(this);
    public interface IPlayerControlsActions
    {
        void OnRoot(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnUnRoot(InputAction.CallbackContext context);
    }
    public interface IRootedActions
    {
        void OnGrow(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
    }
}
